debug: True
dbengine: django.db.backends.mysql
dbname: mydb
dbuser: mydbuser
dbpassword: myterribledbpassword
dbhost: localhost
dbport: 3306
git_rev: master
git_repo: git@54.235.110.147:/git/updatecenter.git